# Generated by Django 3.0.3 on 2020-02-26 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('num_employe', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('tel', models.CharField(max_length=10)),
                ('adresse', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=50)),
                ('admin', models.BooleanField()),
                ('num_permis', models.CharField(max_length=9, null=True)),
                ('date_de_debut', models.DateField(null=True)),
                ('date_de_fin', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conduire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_prise', models.IntegerField()),
                ('date_prise', models.DateField()),
                ('km_restit', models.IntegerField(null=True)),
                ('date_restit', models.DateField(auto_now=True, null=True)),
                ('num_employe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employe.Employe')),
            ],
        ),
        migrations.CreateModel(
            name='Amende',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('infraction', models.CharField(max_length=255)),
                ('montant', models.IntegerField()),
                ('num_employe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employe.Employe')),
            ],
        ),
    ]
