# Generated by Django 3.0.3 on 2020-04-05 21:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conduire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_prise', models.IntegerField()),
                ('date_et_temps_de_prise', models.DateTimeField(default=datetime.datetime.now)),
                ('km_restit', models.IntegerField(blank=True, null=True)),
                ('date_et_temps_de_restitution', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Conduire',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default='media/default.png', upload_to='profils')),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=10)),
                ('adresse', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=50)),
                ('num_permis', models.CharField(max_length=9, null=True)),
                ('date_de_debut', models.DateField(null=True)),
                ('date_de_fin', models.DateField(blank=True, null=True)),
                ('id_photo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employe.Photo')),
                ('id_vehicule', models.ManyToManyField(blank=True, through='employe.Conduire', to='vehicule.Vehicule')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='conduire',
            name='id_employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employe.Employe'),
        ),
        migrations.AddField(
            model_name='conduire',
            name='id_vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicule.Vehicule'),
        ),
        migrations.CreateModel(
            name='Amende',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('infraction', models.CharField(max_length=255)),
                ('montant', models.IntegerField()),
                ('id_employe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employe.Employe')),
                ('id_vehicule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicule.Vehicule')),
            ],
        ),
    ]
