# Generated by Django 3.0.3 on 2020-04-05 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'photo', 'verbose_name_plural': 'photos'},
        ),
    ]
