# Generated by Django 3.0.3 on 2020-02-26 18:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vehicule', '0001_initial'),
        ('employe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amende',
            name='id_vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicule.Vehicule'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conduire',
            name='id_vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicule.Vehicule'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employe',
            name='id_vehicule',
            field=models.ManyToManyField(through='employe.Conduire', to='vehicule.Vehicule'),
        ),
    ]
