# Generated by Django 3.0.3 on 2020-02-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0002_auto_20200226_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='date_de_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
