# Generated by Django 3.0.3 on 2020-03-07 23:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0003_auto_20200227_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conduire',
            options={'verbose_name_plural': 'Conduire'},
        ),
        migrations.AlterField(
            model_name='conduire',
            name='date_prise',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 7, 23, 18, 51, 817823)),
        ),
        migrations.AlterField(
            model_name='conduire',
            name='date_restit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conduire',
            name='km_restit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='num_employe',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
