# Generated by Django 3.0.3 on 2020-04-10 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0003_employe_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='is_admin',
        ),
    ]
