# Generated by Django 3.0.3 on 2020-03-22 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0004_auto_20200319_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conduire',
            name='date_et_temps_de_prise',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 22, 13, 50, 15, 591651)),
        ),
    ]
