# Generated by Django 3.0.3 on 2020-04-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0004_remove_employe_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conduire',
            name='km_prise',
            field=models.IntegerField(null=True),
        ),
    ]
