# Generated by Django 3.0.3 on 2020-03-09 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicule', '0002_auto_20200307_2318'),
        ('employe', '0004_auto_20200307_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conduire',
            name='date_prise',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 9, 17, 53, 20, 703042)),
        ),
        migrations.AlterField(
            model_name='employe',
            name='id_vehicule',
            field=models.ManyToManyField(null=True, through='employe.Conduire', to='vehicule.Vehicule'),
        ),
    ]
