# Generated by Django 3.0.3 on 2020-03-09 22:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicule', '0002_auto_20200307_2318'),
        ('employe', '0005_auto_20200309_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conduire',
            name='date_prise',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 9, 22, 34, 34, 299011)),
        ),
        migrations.AlterField(
            model_name='employe',
            name='id_vehicule',
            field=models.ManyToManyField(through='employe.Conduire', to='vehicule.Vehicule'),
        ),
    ]
