# Generated by Django 3.0.3 on 2020-03-10 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicule', '0002_auto_20200307_2318'),
        ('employe', '0006_auto_20200309_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conduire',
            name='date_prise',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 10, 14, 52, 19, 664371)),
        ),
        migrations.AlterField(
            model_name='employe',
            name='id_vehicule',
            field=models.ManyToManyField(blank=True, through='employe.Conduire', to='vehicule.Vehicule'),
        ),
    ]
