# Generated by Django 3.0.3 on 2020-03-31 23:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0007_auto_20200331_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conduire',
            name='date_et_temps_de_prise',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 31, 23, 44, 41, 881345)),
        ),
    ]
