# Generated by Django 3.0.3 on 2020-03-22 13:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vehicule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='prochain_controle_technique',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicule',
            name='validite_assurance',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
