# Generated by Django 3.0.3 on 2020-04-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicule',
            name='prochain_controle_technique',
        ),
        migrations.AddField(
            model_name='vehicule',
            name='prochain_controle_technique_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='prochain_entretien_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='prochain_entretien_km',
            field=models.IntegerField(null=True),
        ),
    ]
