# Generated by Django 3.0.3 on 2020-04-14 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicule', '0002_auto_20200414_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicule',
            old_name='prochain_controle_technique_date',
            new_name='prochain_controle_technique',
        ),
    ]
