# Generated by Django 3.0.3 on 2020-03-31 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicule', '0002_auto_20200322_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='entretien',
            name='km',
            field=models.IntegerField(default=422),
            preserve_default=False,
        ),
    ]
