# Generated by Django 3.0.3 on 2020-04-14 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicule', '0003_auto_20200414_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='prochain_controle_technique',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='prochain_entretien_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='prochain_entretien_km',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
