# Generated by Django 3.0.3 on 2020-04-15 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicule', '0004_auto_20200414_2126'),
        ('conducteur', '0005_messageprobleme_solved'),
        ('dashboard', '0003_auto_20200415_1540'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together={('id_vehicule', 'id_message', 'is_ct', 'is_entretien_date', 'is_entretien_km')},
        ),
    ]
