# Generated by Django 3.0.3 on 2020-04-15 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20200415_1829'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notification',
            table='notification',
        ),
    ]
