# Generated by Django 3.0.3 on 2020-04-15 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20200415_1831'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notification',
            table='dashboard_notification',
        ),
    ]
