# Generated by Django 3.0.3 on 2020-04-15 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20200415_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='id_message',
        ),
    ]
