# Generated by Django 3.0.3 on 2020-04-15 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_notification_id_message'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notification',
            table=None,
        ),
    ]
