# Generated by Django 3.0.3 on 2020-04-15 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20200415_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='is_entretien_date',
            new_name='is_assurance',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='is_entretien_km',
            new_name='is_entretien',
        ),
    ]
