# Generated by Django 3.0.3 on 2020-04-28 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20200428_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='diff',
        ),
    ]
