# Generated by Django 3.0.3 on 2020-04-28 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_remove_notification_diff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_diff',
        ),
    ]
