# Generated by Django 3.0.3 on 2020-04-12 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employe', '0006_auto_20200411_1953'),
        ('vehicule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageProbleme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('id_employe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employe.Employe')),
                ('id_vehicule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicule.Vehicule')),
            ],
        ),
    ]
