# Generated by Django 3.0.3 on 2020-04-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conducteur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageprobleme',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
