# Generated by Django 3.0.3 on 2020-04-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conducteur', '0002_messageprobleme_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageprobleme',
            name='sujet',
            field=models.CharField(default='test', max_length=20),
            preserve_default=False,
        ),
    ]
