# Generated by Django 3.0.3 on 2020-04-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conducteur', '0003_messageprobleme_sujet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageprobleme',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
