# Generated by Django 3.0.3 on 2020-04-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conducteur', '0004_auto_20200413_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageprobleme',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
